apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: billy/myapp:latest
        imagePullPolicy: Always  # Optional: Ensures pulling the image always on deployment update
        ports:
        - containerPort: 8080
