apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        app1:myapp
    spec:
      containers:
      - name: myapp
        image: billy/myapp:latest
        ports:
        - containerPort: 8080
